name: build
on:
  push:
  pull_request:

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: prettier
        run: npx prettier --check .
